import { Location } from './types';

export const locations: Location[] = [
  {
    "id": "sultanahmet-koftecisi",
    "name": "Tarihi Sultanahmet Köftecisi Selim Usta",
    "category": "Köfte, Yöresel",
    "shortDescription": "1920'den beri hizmet veren tarihi köfteci.",
    "description": "İstanbul'un en popüler lezzet duraklarından biri olan bu asırlık dükkan, köfteleri, piyazı ve irmik helvasıyla meşhurdur.",
    "lat": 41.008035,
    "lng": 28.976865,
    "address": "Alemdar Mah, Divan Yolu Cd. No:12, 34110 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1627308595229-7830f5c90683?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "10:30 - 23:00", "phoneNumber": "+90 216 207 13 15", "enCategory": "Meatballs, Local", "enShortDescription": "Historical meatball restaurant that has been serving since 1920.", "enDescription": "This century-old shop, one of the most popular taste stops in Istanbul, is famous for its meatballs, blarney and semolina halva." },
  {
    "id": "hafiz-mustafa-1864",
    "name": "Hafız Mustafa 1864",
    "category": "Tatlı, Lokum, Baklava",
    "shortDescription": "Osmanlı'dan günümüze uzanan tatlı mirası.",
    "description": "1864 yılında kurulan Hafız Mustafa, Osmanlı saray kültüründen gelen tatlı, lokum, baklava ve muhallebi çeşitleriyle İstanbul'un simge mekanlarından biridir.",
    "lat": 41.014238,
    "lng": 28.976159,
    "address": "Hobyar, Hamidiye Cd. No:84, 34420 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1598165039281-2292f392ddb1?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "07:00 - 02:00", "phoneNumber": "+90 212 214 16 20", "enCategory": "Dessert, Turkish Delight, Baklava", "enShortDescription": "A sweet heritage extending from the Ottoman Empire to the present day.", "enDescription": "Founded in 1864, Hafız Mustafa is one of the symbolic places of Istanbul with its desserts, Turkish delight, baklava and pudding varieties originating from the Ottoman palace culture." },
  {
    "id": "vefa-bozacisi",
    "name": "Tarihi Vefa Bozacısı",
    "category": "İçecek, Geleneksel",
    "shortDescription": "1876'dan beri aynı dükkanda mermer küplerle servis yapan efsanevi adres.",
    "description": "Kış aylarının vazgeçilmez lezzeti bozayı İstanbul'da en iyi sunan yerdir.",
    "lat": 41.015701,
    "lng": 28.956891,
    "address": "Vefa, Katip Çelebi Cd. No:104/1, 34134 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1588667633215-674e2d365516?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "08:00 - 00:00", "phoneNumber": "+90 216 221 19 25", "enCategory": "Beverage, Traditional", "enShortDescription": "The legendary address that has been serving marble cubes in the same shop since 1876.", "enDescription": "It is the best place in Istanbul to offer the indispensable taste of the winter months, the grizzly bear." },
  {
    "id": "karakoy-gulluoglu",
    "name": "Karaköy Güllüoğlu",
    "category": "Baklava",
    "shortDescription": "Baklava denince akla ilk gelen efsanevi marka.",
    "description": "Nadircan Güllü tarafından Karaköy'de açılan bu mağaza, Antep fıstıklı, cevizli, şöbiyet, ve daha birçok baklava çeşidinin İstanbul'daki en iyi temsilcilerindendir.",
    "lat": 41.023249,
    "lng": 28.978912,
    "address": "Kemankeş Karamustafa Paşa, Kemankeş Cd. No:67, 34425 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1628186107317-02796abec1c7?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "07:00 - 01:00", "phoneNumber": "+90 212 228 22 30", "enCategory": "Baklava", "enShortDescription": "The first thing that comes to mind when talking about baklava is the legendary brand.", "enDescription": "This store, opened by Nadircan Güllü in Karaköy, is one of the best representatives of pistachio, walnut, şöbiyet, and many other baklava varieties in Istanbul." },
  {
    "id": "kizilkayalar",
    "name": "Kızılkayalar",
    "category": "Sokak Lezzeti",
    "shortDescription": "Taksim Meydanı'nın sembolü, Islak Hamburger'in mucidi.",
    "description": "Gecenin bir yarısı İstiklal Caddesi çıkışında kalabalığın hiç eksik olmadığı Kızılkayalar'ın buharlı ıslak hamburgeri İstanbullular için vazgeçilmez bir sokak klasiktir.",
    "lat": 41.037061,
    "lng": 28.985023,
    "address": "Sıraselviler Cd. No:2, 34437 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "08:00 - 05:00", "phoneNumber": "+90 216 235 25 35", "enCategory": "Street Taste", "enShortDescription": "The symbol of Taksim Square, the inventor of the Wet Hamburger.", "enDescription": "The steamy wet hamburger of Kızılkayalar, where there is always a crowd at the exit of Istiklal Street in the middle of the night, is an indispensable street classic for Istanbulites." },
  {
    "id": "inci-pastanesi",
    "name": "İnci Pastanesi",
    "category": "Pastane, Profiterol",
    "shortDescription": "Profiterol denince İstanbul'da tek geçilen, efsanevi pastane.",
    "description": "1944 yılında Luka Zigoris tarafından kurulan İnci Pastanesi, özel çikolata soslu profiterolüyle yıllardır aynı tarifsiz lezzeti sunmaya devam etmektedir.",
    "lat": 41.034500,
    "lng": 28.980512,
    "address": "Şehit Muhtar, Mis Sk. 18/A, 34435 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1605807646983-377bc5a76493?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "07:00 - 23:00", "phoneNumber": "+90 212 242 28 40", "enCategory": "Patisserie, Profiteroles", "enShortDescription": "When it comes to profiteroles, the only thing mentioned in Istanbul is the legendary patisserie.", "enDescription": "Founded by Luka Zigoris in 1944, İnci Patisserie continues to offer the same indescribable taste for years with its special chocolate sauce profiteroles." },
  {
    "id": "sariyer-borekcisi",
    "name": "Tarihi Meşhur Sarıyer Börekçisi",
    "category": "Börek, Kahvaltı",
    "shortDescription": "1895'ten bugüne kıymalı kuşüzümlü nefis Sarıyer Böreği.",
    "description": "Boğaza nazır Sarıyer semtinin adını böreğiyle duyurmuş mekanıdır. İncecik açılmış hamuru ile kıymalı börek yemek sabah İstanbullularının vazgeçilmez ritüellerindendir.",
    "lat": 41.165215,
    "lng": 29.054326,
    "address": "Merkez Mah, Yeni Mahalle Cd No:50, 34450 Sarıyer/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1616149955740-424a50f14652?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "06:00 - 15:00", "phoneNumber": "+90 216 249 31 45", "enCategory": "Pastry, Breakfast", "enShortDescription": "Delicious Sarıyer Pastry with minced meat and currants since 1895.", "enDescription": "It is the place in the Sarıyer district overlooking the Bosphorus that made its name known with its pastry. Eating minced meat pastry with thinly rolled dough is an indispensable ritual for Istanbulites in the morning." },
  {
    "id": "kanlica-yogurdu",
    "name": "Tarihi Kanlıca Yoğurdu (İsmailağa)",
    "category": "Yoğurt, Geleneksel",
    "shortDescription": "Üzerine pudra şekeri dökülerek yenilen meşhur Kanlıca Yoğurdu.",
    "description": "Boğaziçi vapur seferlerinin vazgeçilmez duraklarından olan Kanlıca'da pudra şekeriyle servis edilen bu özel yoğurt tam bir yalı ve boğaz kültürü mirasıdır.",
    "lat": 41.099182,
    "lng": 29.065516,
    "address": "Kanlıca Mah, Barış Manço Cd. No:59, 34810 Beykoz/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1551024506-0cb7e69f8ed1?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "08:30 - 23:30", "phoneNumber": "+90 212 256 34 50", "enCategory": "Yogurt, Traditional", "enShortDescription": "The famous Kanlıca Yoghurt, which is eaten with powdered sugar on top.", "enDescription": "This special yoghurt, served with powdered sugar in Kanlıca, one of the indispensable stops of the Bosphorus ferry trips, is a true heritage of the waterside and Bosphorus culture." },
  {
    "id": "pandeli-restaurant",
    "name": "Pandeli Restaurant",
    "category": "Geleneksel Türk Mutfağı",
    "shortDescription": "Mısır Çarşısı'nın üst katında yer alan ikonik lokanta.",
    "description": "Çinili duvarları ve tarihi atmosferiyle büyüleyen Pandeli, hünkar beğendi ve dönerli böreğiyle İstanbul'un klasikleşmiş yeme içme mekanlarının başında gelir.",
    "lat": 41.016335,
    "lng": 28.971032,
    "address": "Rüstem Paşa, Mısır Çarşısı No:1, 34116 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "11:30 - 19:00", "phoneNumber": "+90 216 263 37 55", "enCategory": "Traditional Turkish Cuisine", "enShortDescription": "The iconic restaurant located on the upper floor of the Spice Bazaar.", "enDescription": "Fascinating with its tiled walls and historical atmosphere, Pandeli is one of the classic eating and drinking venues of Istanbul with its Hünkar betti and dönerli pastry." },
  {
    "id": "balikci-sabahattin",
    "name": "Balıkçı Sabahattin",
    "category": "Deniz Ürünleri, Balık",
    "shortDescription": "Cankurtaran'da ahşap bir köşkte unutulmaz deniz ürünleri.",
    "description": "Mezeleri, taptaze balıkları ve tarihi yarımada içindeki eşsiz konumuyla Balıkçı Sabahattin, İstanbul'un en özel balık restoranlarından birisidir.",
    "lat": 41.003923,
    "lng": 28.981881,
    "address": "Cankurtaran, Şehit Hasan Kuyu Sk. No:1, 34122 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "12:00 - 00:00", "phoneNumber": "+90 212 270 40 60", "enCategory": "Seafood, Fish", "enShortDescription": "Unforgettable seafood in a wooden mansion in Cankurtaran.", "enDescription": "With its appetizers, fresh fish and unique location within the historical peninsula, Balıkçı Sabahattin is one of the most special fish restaurants in Istanbul." },
  {
    "id": "haci-abdullah",
    "name": "Hacı Abdullah Lokantası",
    "category": "Osmanlı Mutfağı, Sulu Yemek",
    "shortDescription": "Ahilik teşkilatı geleneğiyle 1888'den beri hizmette.",
    "description": "Beyoğlu'nun göbeğinde Osmanlı mutfağının en seçkin zeytinyağlıları, kompostoları ve tencere yemeklerini bulabileceğiniz, ustadan çırağa devredilen bir efsane.",
    "lat": 41.035176,
    "lng": 28.980646,
    "address": "Hüseyinağa, Atıf Yılmaz Cd. No:9/A, 34435 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544148103-0773d1052bfc?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:00 - 22:30", "phoneNumber": "+90 216 277 43 65", "enCategory": "Ottoman Cuisine, Stylish Food", "enShortDescription": "It has been in service since 1888 with the tradition of the Ahi organization.", "enDescription": "It is a legend passed down from master to apprentice, where you can find the most distinguished olive oil dishes, compotes and casserole dishes of the Ottoman cuisine in the heart of Beyoğlu." },
  {
    "id": "kalkanoglu-pilavi",
    "name": "Tarihi Kalkanoğlu Pilavı",
    "category": "Pilav, Ev Yemeği",
    "shortDescription": "Trabzon geleneğini İstanbul'a taşıyan tarihi pilavcı.",
    "description": "Osmanlı Saray mutfağından gelen ve özel et suyu ile Trabzon tereyağı kullanılarak hazırlanan tarihi Kalkanoğlu pilavı, kendi müdavimlerini yaratmış bir mekandır.",
    "lat": 41.035728,
    "lng": 28.980838,
    "address": "Kuloğlu, Ayhan Işık Sk. No:16, 34433 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=800&q=80",
    "rating": 4.2,
    "workingHours": "11:30 - 21:00", "phoneNumber": "+90 212 284 46 70", "enCategory": "Rice, Homemade Food", "enShortDescription": "The historical pilaf maker who brought the Trabzon tradition to Istanbul.", "enDescription": "The historical Kalkanoğlu pilaf, which comes from the Ottoman Palace cuisine and is prepared using special broth and Trabzon butter, is a place that has created its own regulars." },
  {
    "id": "seyhmuz-kebap",
    "name": "Şeyhmuz Kebap Salonu",
    "category": "Kebap, Et",
    "shortDescription": "Çemberlitaş'ın arka sokaklarında gizli bir kebap mabedi.",
    "description": "Zırhla çekilen etlerden yapılan özel Şeyhmuz Kebabı ve satır kıyması ürünleriyle gerçek et lezzetini arayanların Çemberlitaş'taki değişmez uğrak yeridir.",
    "lat": 41.008432,
    "lng": 28.971510,
    "address": "Mollafenari, Medrese Sk. No:2, 34120 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "11:30 - 20:30", "phoneNumber": "+90 216 291 49 75", "enCategory": "Kebab, Meat", "enShortDescription": "A hidden kebab temple in the back streets of Çemberlitaş.", "enDescription": "It is a regular stop in Çemberlitaş for those looking for the real meat taste with its special Şeyhmuz Kebab and minced meat products made from shredded meat." },
  {
    "id": "kanaat-lokantasi",
    "name": "Kanaat Lokantası",
    "category": "Esnaf Lokantası",
    "shortDescription": "Üsküdar'da yarım asırlık klasik esnaf lokantası lezzetleri.",
    "description": "Özelliğini bozmadan günümüze gelmiş, zeytinyağlı enginarı, Özbek pilavı, elbasan tavası ve sütlü tatlılarıyla Anadolu yakasının vazgeçilmez lezzet duraklarından biridir.",
    "lat": 41.026410,
    "lng": 29.015764,
    "address": "Sultantepe, Selmani Pak Cd. No:9, 34674 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "06:00 - 22:30", "phoneNumber": "+90 212 298 52 80", "enCategory": "Esnaf Restaurant", "enShortDescription": "Half a century old classic tradesman restaurant flavors in Üsküdar.", "enDescription": "It is one of the indispensable taste stops of the Anatolian side, with its olive oil artichokes, Uzbek pilaf, elbasan pan and milk desserts, which has survived to the present day without losing its speciality." },
  {
    "id": "yanyali-fehmi",
    "name": "Yanyalı Fehmi Lokantası",
    "category": "Osmanlı ve Türk Mutfağı",
    "shortDescription": "1919'dan beri Kadıköy Çarşı'nın incisi.",
    "description": "Yanya'dan göç eden bir ailenin kurduğu esnaf lokantası. Yanya köftesi ve mevsimsel ev yemekleri konusunda Anadolu yakasında bir klasiktir.",
    "lat": 40.989803,
    "lng": 29.025345,
    "address": "Osmanağa, Yağlıkçı İsmail Sk. No:1, 34714 Kadıköy/İstanbul",
    "imageUrl": "https://plus.unsplash.com/premium_photo-1664472637341-3ec829d1f4da?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "09:00 - 22:00", "phoneNumber": "+90 216 305 55 85", "enCategory": "Ottoman and Turkish Cuisine", "enShortDescription": "The pearl of Kadıköy Bazaar since 1919.", "enDescription": "A tradesmen's restaurant founded by a family that emigrated from Yanya. It is a classic on the Anatolian side when it comes to Yanya meatballs and seasonal home cooking." },
  {
    "id": "ciya-sofrasi",
    "name": "Çiya Sofrası",
    "category": "Yöresel Mutfak, Anadolu Lezzetleri",
    "shortDescription": "Unutulmaya yüz tutmuş Anadolu lezzetlerinin müzesi.",
    "description": "Musa Dağdeviren'in kurduğu Çiya, Anadolu'nun dört bir yanından toplanan tariflerle, mevsimine uygun olarak kebap ve tencere yemeklerini aynı çatı altında sunan bir lezzet vahasıdır.",
    "lat": 40.988647,
    "lng": 29.024564,
    "address": "Caferağa, Güneşli Bahçe Sk. No:43, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "11:00 - 22:00", "phoneNumber": "+90 212 312 58 90", "enCategory": "Local Cuisine, Anatolian Flavors", "enShortDescription": "The museum of almost forgotten Anatolian delicacies.", "enDescription": "Founded by Musa Dağdeviren, Çiya is an oasis of taste that offers seasonal kebab and casserole dishes under the same roof, with recipes collected from all over Anatolia." },
  {
    "id": "baylan-pastanesi",
    "name": "Baylan Pastanesi",
    "category": "Pastane, Tatlı",
    "shortDescription": "Kup Griye mucidi Kadıköy'de nostaljik tatlıcı.",
    "description": "Cumhuriyet dönemi İstanbul'unun en eski çalışan pastanelerinden biri. Karamel, badem ve vanilyalı dondurma ile yapılan muhteşem Kup Griye hala aynı lezzette sunulmaktadır.",
    "lat": 40.989399,
    "lng": 29.024090,
    "address": "Caferağa, Muvakkithane Cd. No:9/A, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559598467-f8b76c8105d0?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "07:30 - 22:00", "phoneNumber": "+90 216 319 61 95", "enCategory": "Patisserie, Desserts", "enShortDescription": "The inventor of Kup Griye is a nostalgic dessert shop in Kadıköy.", "enDescription": "One of the oldest working patisseries in Istanbul during the Republican era. The magnificent Kup Griye, made with caramel, almonds and vanilla ice cream, is still offered in the same taste." },
  {
    "id": "fazil-bey",
    "name": "Fazıl Bey'in Türk Kahvesi",
    "category": "Kahve, İçecek",
    "shortDescription": "Taze kavrulmuş odun ateşinde Türk Kahvesi.",
    "description": "Kadıköy Çarşısı'nın ara sokağında, dibek kahvesini taptaze kavurarak sunan tarihi kahvecidir. Damla sakızlı kahvesi oldukça popülerdir.",
    "lat": 40.989501,
    "lng": 29.026135,
    "address": "Caferağa, Serasker Cd. No:1, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "08:30 - 23:30", "phoneNumber": "+90 212 326 64 10", "enCategory": "Coffee, Beverage", "enShortDescription": "Freshly roasted wood-fired Turkish Coffee.", "enDescription": "It is a historical coffee shop in the side street of Kadıköy Bazaar, serving freshly roasted Dibek coffee. Mastic coffee is very popular." },
  {
    "id": "haci-bekir",
    "name": "Ali Muhiddin Hacı Bekir",
    "category": "Lokum, Şekerleme",
    "shortDescription": "1777'den bu yana Bahçekapı'da lokumun mucidi.",
    "description": "Dünyaya 'Turkish Delight'ı tanıtan isimdir. Gül, fıstık, sakız aromalı tarihi lokumlar ve akide şekerleri hala aynı tarif ve kalitededir.",
    "lat": 41.015795,
    "lng": 28.973415,
    "address": "Hobyar, Zahire Borsası Sk. No:1, 34112 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1549491689-d10292bc9da6?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "08:00 - 20:00", "phoneNumber": "+90 216 333 67 15", "enCategory": "Turkish Delight, Confectionery", "enShortDescription": "The inventor of Turkish delight in Bahçekapı since 1777.", "enDescription": "He is the name that introduced 'Turkish Delight' to the world. Rose, pistachio and gum flavored historical Turkish delights and rock candies are still of the same recipe and quality." },
  {
    "id": "namli-gurme",
    "name": "Namlı Gurme",
    "category": "Kahvaltı, Şarküteri",
    "shortDescription": "Karaköy'de kahvaltının en çeşitli ve lezzetli hali.",
    "description": "Şarküteri reyonundan seçtiğiniz envai çeşit peynir, zeytin, pastırma ve sıcaklarla kendi kahvaltı tabağınızı hazırlayabileceğiniz bir İstanbul kahvaltı klasiğidir.",
    "lat": 41.023246,
    "lng": 28.978018,
    "address": "Kemankeş Karamustafa Paşa, Rıhtım Cd. No:1/1, 34425 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "07:00 - 22:00", "phoneNumber": "+90 212 340 70 20", "enCategory": "Breakfast, Deli", "enShortDescription": "The most diverse and delicious version of breakfast in Karaköy.", "enDescription": "It is an Istanbul breakfast classic where you can prepare your own breakfast plate with a wide variety of cheeses, olives, pastrami and hot foods that you choose from the delicatessen section." },
  {
    "id": "emirgan-sutis",
    "name": "Sütiş",
    "category": "Kahvaltı, Sütlü Tatlı",
    "shortDescription": "Boğaz manzarasına karşı kahvaltı ve kazandibi.",
    "description": "Erkenden gidip denize nazır bir masa kapılarak yapılan su börekli kahvaltıların ve enfes sütlü tatlıların Emirgan'daki sembol ismidir.",
    "lat": 41.104443,
    "lng": 29.055815,
    "address": "Emirgan, Sakıp Sabancı Cd. No:1/3, 34467 Sarıyer/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1495147466023-af5c19cb3738?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "06:00 - 02:00", "phoneNumber": "+90 216 347 73 25", "enCategory": "Breakfast, Milk Dessert", "enShortDescription": "Breakfast and Kazandibi overlooking the Bosphorus.", "enDescription": "It is the symbolic name in Emirgan for pastry breakfasts and delicious milk desserts made by going early and grabbing a table overlooking the sea." },
  {
    "id": "kurukahveci",
    "name": "Kurukahveci Mehmet Efendi",
    "category": "Kahve",
    "shortDescription": "Mısır Çarşısı'nın kahve kokan köşesi, 1871'den beri.",
    "description": "Eminönü'nde sıraya girip taze çekilmiş kahve almadan çarşı gezisi bitmiş sayılmaz. İstanbul sokaklarına yayılan taze kahve kokusunun merkezidir.",
    "lat": 41.016335,
    "lng": 28.971200,
    "address": "Rüstem Paşa, Tahmis Sk. No:66, 34116 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80",
    "rating": 4.9,
    "workingHours": "08:00 - 19:30", "phoneNumber": "+90 212 354 76 30", "enCategory": "Coffee", "enShortDescription": "The coffee-scented corner of the Spice Bazaar, since 1871.", "enDescription": "The market trip is not over without standing in line in Eminönü and buying freshly ground coffee. It is the center of the fresh coffee smell spreading through the streets of Istanbul." },
  {
    "id": "lale-iskembecisi",
    "name": "Lale İşkembecisi",
    "category": "Çorba, İşkembe",
    "shortDescription": "Beyoğlu gecelerinin son durağı.",
    "description": "1960'lardan beri Taksim'de eğlence sonrası çorbacı ritüelinin başrol oyuncusudur. Sarımsak ve sirkeli işkembesiyle ünlüdür.",
    "lat": 41.037500,
    "lng": 28.983000,
    "address": "Şehit Muhtar, Tarlabaşı Blv. No:5, 34435 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1606850734289-4da6f10c6604?auto=format&fit=crop&w=800&q=80",
    "rating": 4.1,
    "workingHours": "24 Saat Açık", "phoneNumber": "+90 216 361 79 35", "enCategory": "Soup, Tripe", "enShortDescription": "The last stop of Beyoğlu nights.", "enDescription": "He has been the leading actor in the after-entertainment soup restaurant ritual in Taksim since the 1960s. It is famous for its tripe with garlic and vinegar." },
  {
    "id": "merkez-efendi",
    "name": "Tarihi Merkez Efendi Köftecisi",
    "category": "Köfte",
    "shortDescription": "Zeytinburnu'nun piyaz tutkunlarını çeken efsanevi köftecisi.",
    "description": "Merkez Efendi türbesinin yanındaki bu samimi dükkanda yiyeceğiniz sulu köfteler, piyaz ve ayran üçlüsü şehrin unutulmaz tatlarındandır.",
    "lat": 41.016584,
    "lng": 28.924040,
    "address": "Merkezefendi, Dere Sk. No:14, 34015 Zeytinburnu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "10:00 - 22:00", "phoneNumber": "+90 212 368 82 40", "enCategory": "Meatball", "enShortDescription": "Zeytinburnu's legendary meatball restaurant that attracts piyaz lovers.", "enDescription": "The juicy meatballs, blarney and ayran trio you will eat in this friendly shop next to the Merkez Efendi tomb are among the unforgettable tastes of the city." },
  {
    "id": "cinaralti",
    "name": "Tarihi Çınaraltı Çay Bahçesi",
    "category": "Çay Bahçesi, Kahvaltı",
    "shortDescription": "Boğaz'ın sularına nazır demleme çay keyfi.",
    "description": "Çengelköy'de asırlık çınar ağaçlarının altında, dışarıdan getirdiğiniz böreklerle kendi kahvaltınızı yapıp demli çay yudumlayabileceğiniz huzur dolu mekan.",
    "lat": 41.050516,
    "lng": 29.052028,
    "address": "Çengelköy, Çınarlı Cami Sk. No:4, 34680 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1577318182747-d586ea2deba4?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "24 Saat Açık", "phoneNumber": "+90 216 375 85 45", "enCategory": "Tea Garden, Breakfast", "enShortDescription": "Enjoying brewed tea overlooking the waters of the Bosphorus.", "enDescription": "A peaceful place under the centuries-old plane trees in Çengelköy, where you can have your own breakfast with pastries brought from outside and sip strong tea." },
  {
    "id": "sabirtasi",
    "name": "Sabırtaşı İçli Köfte",
    "category": "Sokak Lezzeti, Yöresel",
    "shortDescription": "İstiklal Caddesi'nin en lezzetli köşebaşı.",
    "description": "Yıllardır İstiklal Caddesi üzerinde beyaz önlüğüyle içli köfte satan ailenin el emeği, incecik cevizli içli köfteleri çok meşhurdur.",
    "lat": 41.033500,
    "lng": 28.977500,
    "address": "Asmalı Mescit, İstiklal Cd. No:112, 34430 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1621845182046-cf906a599b50?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "12:00 - 20:00", "phoneNumber": "+90 212 382 88 50", "enCategory": "Street Food, Local", "enShortDescription": "The most delicious corner of Istiklal Street.", "enDescription": "The handmade, thin, walnut-filled stuffed meatballs of the family, who has been selling stuffed meatballs with their white aprons on Istiklal Street for years, are very famous." },
  {
    "id": "konyali-lokantasi",
    "name": "Konyalı Lokantası",
    "category": "Osmanlı Mutfağı",
    "shortDescription": "Topkapı Sarayı içinde padişahlara layık şerbet ve lezzetler.",
    "description": "Saray manzarasında Türk ve Osmanlı saray mutfağının en nadide örneklerini sunar. Turistler ve klasik tatları arayanlar için muazzamdır.",
    "lat": 41.011867,
    "lng": 28.983226,
    "address": "Cankurtaran, Topkapı Sarayı Müzesi İçi, 34122 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1548943487-a2e4b43b5851?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "09:00 - 17:00", "phoneNumber": "+90 216 389 91 55", "enCategory": "Ottoman Cuisine", "enShortDescription": "Sherbets and delicacies worthy of sultans in Topkapı Palace.", "enDescription": "It offers the rarest examples of Turkish and Ottoman palace cuisine in a palace view. It is great for tourists and those looking for classic tastes." },
  {
    "id": "durumzade",
    "name": "Dürümzade",
    "category": "Dürüm, Kebap",
    "shortDescription": "Anthony Bourdain'i bile büyüleyen dürümcü.",
    "description": "Lavaşını özel baharatlı sosa bulayıp mangalda ısıtan, içi sulu şişlerle doldurulmuş Beyoğlu'nun kült dürümcüsüdür.",
    "lat": 41.036000,
    "lng": 28.978500,
    "address": "Hüseyinağa, Kamer Hatun Cd. 26/A, 34435 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1626081156828-56eb0f5761a6?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:30 - 04:00", "phoneNumber": "+90 212 396 94 60", "enCategory": "Wrap, Kebab", "enShortDescription": "The wrap maker that fascinated even Anthony Bourdain.", "enDescription": "It is the cult wrap of Beyoğlu, whose lavash is filled with juicy skewers, dipped in special spicy sauce and heated on a barbecue." },
  {
    "id": "kiyi-restaurant",
    "name": "Kıyı Restaurant",
    "category": "Deniz Ürünleri",
    "shortDescription": "Tarabya'nın elit ve klasikleşmiş balıkçısı.",
    "description": "Lakerdası, taraması ve kusursuz servis anlayışıyla İstanbul cemiyet hayatının ve gurmelerinin 1960'lardan beri değişmez tercihidir.",
    "lat": 41.140833,
    "lng": 29.056388,
    "address": "Tarabya, Haydar Aliyev Cd. No:186, 34457 Sarıyer/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559466273-d95e72debaf8?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "12:00 - 00:00", "phoneNumber": "+90 216 403 97 65", "enCategory": "Seafood", "enShortDescription": "Tarabya's elite and classic fisherman.", "enDescription": "It has been the constant choice of Istanbul's social life and gourmets since the 1960s with its Lakerdasi, delicious food and perfect service approach." },
  {
    "id": "develi-kebab",
    "name": "Develi Kebap (Samatya)",
    "category": "Kebap, Yöresel",
    "shortDescription": "Antep mutfağının İstanbul'daki kalesi.",
    "description": "Ali Nazik ve fıstıklı kebabı İstanbul'a tanıtan tarihi mekan. Samatya'daki bu merkez dükkan, otantik atmosferini yıllardır korur.",
    "lat": 41.000300,
    "lng": 28.938800,
    "address": "Kocamustafapaşa, Gümüş Yüzük Sk. No:7, 34098 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "12:00 - 23:30", "phoneNumber": "+90 212 410 10 70", "enCategory": "Kebab, Local", "enShortDescription": "The castle of Antep cuisine in Istanbul.", "enDescription": "The historical place that introduced Ali Nazik and pistachio kebab to Istanbul. This central shop in Samatya maintains its authentic atmosphere for years." },
  {
    "id": "tarihi-eminonu",
    "name": "Tarihi Eminönü Balık Ekmekcisi",
    "category": "Sokak Lezzeti, Balık",
    "shortDescription": "Sallanan teknelerde pişen İstanbul klasiği balık ekmek.",
    "description": "Eminönü sahilinde, sallanan sandalların üzerinde pişirilen, bol soğan ve limon eşliğinde sunulan balık ekmek, en otantik sokak lezzetlerindendir.",
    "lat": 41.018200,
    "lng": 28.972300,
    "address": "Hobyar, Rüstem Paşa, Galata Köprüsü Eminönü Ayağı, Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1564613467268-bf0ddb3c220f?auto=format&fit=crop&w=800&q=80",
    "rating": 4.2,
    "workingHours": "10:00 - 22:30", "phoneNumber": "+90 216 417 13 75", "enCategory": "Street Food, Fish", "enShortDescription": "Istanbul classic fish and bread cooked in rocking boats.", "enDescription": "Fish bread, cooked on rocking boats on the Eminönü coast and served with plenty of onion and lemon, is one of the most authentic street delicacies." },
  {
    "id": "ali-baba-kurufasulye",
    "name": "Erzincanlı Ali Baba",
    "category": "Ev Yemeği, Kurufasulye",
    "shortDescription": "Süleymaniye Camii karşısında 1924'ten beri kurufasulye.",
    "description": "Bakır kazanlarda odun ateşinde demlenerek pişen İspir fasulyesi ve tereyağlı pilavıyla Süleymaniye silüetinde efsaneleşmiş esnaf lokantası.",
    "lat": 41.015200,
    "lng": 28.963200,
    "address": "Süleymaniye, Prof. Sıddık Sami Onar Cd. No:11, 34116 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "08:00 - 20:00", "phoneNumber": "+90 212 424 16 80", "enCategory": "Homemade Food, Beans", "enShortDescription": "Baked beans opposite Suleymaniye Mosque since 1924.", "enDescription": "A legendary tradesmen's restaurant in the Suleymaniye skyline with its Ispir beans and buttered rice brewed over wood fire in copper cauldrons." },
  {
    "id": "unkapani-pilavcisi",
    "name": "Meşhur Unkapanı Pilavcısı",
    "category": "Sokak Lezzeti, Pilav",
    "shortDescription": "Gece acıkanların İMÇ blokları önündeki kurtarıcısı.",
    "description": "Nohutlu, tavuklu, bol karabiberli sokak pilavının İstanbul'daki en salaş ve en popüler temsilcisi. Ayran ile birlikte unutulmazdır.",
    "lat": 41.018000,
    "lng": 28.956000,
    "address": "Zeyrek, Atatürk Blv. İMÇ Blokları, 34083 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:00 - 05:00", "phoneNumber": "+90 216 431 19 85", "enCategory": "Street Food, Rice", "enShortDescription": "The savior of those who get hungry at night in front of the İMÇ blocks.", "enDescription": "The shabbiest and most popular representative of street pilaf in Istanbul, with chickpeas, chicken and plenty of black pepper. It is unforgettable with ayran." },
  {
    "id": "asuman",
    "name": "Asuman",
    "category": "Tatlı, Çikolata",
    "shortDescription": "Moda'nın kavanozda gelen çikolata çılgınlığı.",
    "description": "Kendi imalatı çikolatalar ve taze meyvelerle dolu küçük cam kavanoz tatlısı 'Asuman' ile Moda sokaklarında uzun kuyruklar oluşturan popüler tatlıcı.",
    "lat": 40.983000,
    "lng": 29.025000,
    "address": "Caferağa, Şair Nefi Sk. No:9, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1542861619-756184ce1bfb?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "12:00 - 22:30", "phoneNumber": "+90 212 438 22 90", "enCategory": "Dessert, Chocolate", "enShortDescription": "Moda's chocolate craze that comes in a jar.", "enDescription": "A popular dessert shop that creates long queues on the streets of Moda with its small glass jar dessert 'Asuman' filled with its own chocolates and fresh fruits." },
  {
    "id": "bebek-badem",
    "name": "Bebek Badem Ezmecisi",
    "category": "Tatlı, Ezme",
    "shortDescription": "1904'ten beri butik badem ezmesi zarafeti.",
    "description": "Sadece badem, şeker ve limon suyu ile katkısız üretilen, el yapımı eşsiz badem ezmeleri ve fıstık ezmeleri ile Bebek'in tarihi sembolüdür.",
    "lat": 41.077200,
    "lng": 29.043500,
    "address": "Bebek, Cevdet Paşa Cd. No:238/C, 34342 Beşiktaş/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "09:00 - 21:00", "phoneNumber": "+90 216 445 25 95", "enCategory": "Dessert, Paste", "enShortDescription": "Boutique marzipan elegance since 1904.", "enDescription": "It is the historical symbol of Bebek with its unique handmade almond pastes and peanut butters, produced without additives only with almonds, sugar and lemon juice." },
  {
    "id": "mandabatmaz",
    "name": "Mandabatmaz",
    "category": "Kahve",
    "shortDescription": "İstiklal'de yoğun köpüklü, bol telveli kahve molası.",
    "description": "Üzerindeki köpüğü 'manda batmaz' kadar kalın ve yoğun olan efsanevi Türk kahvecisidir. Daracık ara sokakta taburelere dizilip sohbet edilir.",
    "lat": 41.032200,
    "lng": 28.977200,
    "address": "Asmalı Mescit, Olivia Geçidi No:1/A, 34430 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "09:30 - 23:00", "phoneNumber": "+90 212 452 28 10", "enCategory": "Coffee", "enShortDescription": "Coffee break with intense foam and plenty of grounds in Istiklal.", "enDescription": "It is a legendary Turkish coffee shop whose foam is as thick and dense as 'buffalo sinking'. People line up on stools in the narrow alley and chat." },
  {
    "id": "karakoy-balikcisi",
    "name": "Tarihi Karaköy Balıkçısı",
    "category": "Balık, Restoran",
    "shortDescription": "Grifin Han'ın terasından tarihi yarımadaya nazır balık.",
    "description": "1923'ten beri değişmeyen kağıtta levrek lezzeti, sade dekorasyonu ve eşsiz boğaz-Haliç manzarası ile saklı kalmış bir Karaköy incisidir.",
    "lat": 41.023500,
    "lng": 28.974000,
    "address": "Arap Cami, Tersane Cd. Kardeşim Sk. No:30, 34421 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559466273-d95e72debaf8?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "12:00 - 23:00", "phoneNumber": "+90 216 459 31 15", "enCategory": "Fish, Restaurant", "enShortDescription": "Fish overlooking the historical peninsula from the terrace of Grifin Han.", "enDescription": "It is a hidden Karaköy pearl with its taste of sea bass in paper, which has not changed since 1923, its simple decoration and its unique Bosphorus-Golden Horn view." },
  {
    "id": "ficcin",
    "name": "Fıccın",
    "category": "Çerkes Mutfağı, Ev Yemeği",
    "shortDescription": "Beyoğlu Kallavi Sokak'ta nefis Çerkes lezzetleri.",
    "description": "Kallavi sokağının her iki tarafına yayılmış masalarıyla Çerkes mantısı (haluj), özel etli fıccın böreği ve tencere yemekleriyle ünlü sıcak mekan.",
    "lat": 41.033300,
    "lng": 28.976000,
    "address": "Asmalı Mescit, İstiklal Cd. Kallavi Sk. No:13, 34430 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "11:30 - 00:00", "phoneNumber": "+90 212 466 34 20", "enCategory": "Circassian Cuisine, Homemade Food", "enShortDescription": "Delicious Circassian delicacies on Beyoğlu Kallavi Street.", "enDescription": "A hot place with tables spread on both sides of Kallavi Street, famous for its Circassian manti (haluj), special meat pastry and casserole dishes." },
  {
    "id": "koskeroglu",
    "name": "Köşkeroğlu Baklava",
    "category": "Baklava, Kebap",
    "shortDescription": "Karaköy'de Antep baklavasının en güçlü isimlerinden.",
    "description": "Altın sarısı rengi, incecik yufkasıyla tereyağlı fıstıklı Antep baklavası, şöbiyet ve enfes kebap menüsüyle tam bir lezzet merkezidir.",
    "lat": 41.023800,
    "lng": 28.977200,
    "address": "Kemankeş Karamustafa Paşa, Mumhane Cd. No:2/D, 34425 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1598165039281-2292f392ddb1?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "07:30 - 01:00", "phoneNumber": "+90 216 473 37 25", "enCategory": "Baklava, Kebab", "enShortDescription": "One of the strongest names in Antep baklava in Karaköy.", "enDescription": "It is a center of taste with its golden yellow color, thin dough, buttery pistachio pistachio baklava, şöbiyet and delicious kebab menu." },
  {
    "id": "sahin-usta",
    "name": "Dönerci Şahin Usta",
    "category": "Döner",
    "shortDescription": "Kapalıçarşı esnafının kuyruğa girdiği efsane dönerci.",
    "description": "Sadece bir kapı büyüklüğündeki dükkanında, pidenin içinde, özel domates ve soğanla hazırlanan inanılmaz lezzetli ve sulu yaprak döner klasiğidir.",
    "lat": 41.010500,
    "lng": 28.966300,
    "address": "Mollafenari, Kılıçcılar Sk. No:9, 34120 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1529148482759-b35b25c5f217?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "11:00 - 16:30", "phoneNumber": "+90 212 480 40 30", "enCategory": "Rotary", "enShortDescription": "The legendary doner restaurant where Grand Bazaar shopkeepers queue up.", "enDescription": "It is an incredibly delicious and juicy classic of döner kebab, prepared with special tomatoes and onions, inside a pita bread, in a shop the size of just one door." },
  {
    "id": "hocapasa-pidecisi",
    "name": "Tarihi Hocapaşa Pidecisi",
    "category": "Pide",
    "shortDescription": "Sirkeci Hocapaşa sokağında odun ateşinde çıtır pideler.",
    "description": "1964'ten beri açık olan ve odun ateşinde kavurmalı, kıymalı kaşarlı ince hamur pideleri ve sıcak atmosferiyle meşhur pideci.",
    "lat": 41.013500,
    "lng": 28.976500,
    "address": "Hoca Paşa, Hoca Paşa Sk. No:19, 34110 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "11:00 - 21:00", "phoneNumber": "+90 216 487 43 35", "enCategory": "pita", "enShortDescription": "Crispy pitas over a wood fire on Sirkeci Hocapaşa street.", "enDescription": "A pita restaurant that has been open since 1964 and is famous for its thin dough pitas with wood-fired roasting, minced meat and kashar cheese, and its warm atmosphere." },
  {
    "id": "filibe-koftecisi",
    "name": "Meşhur Filibe Köftecisi",
    "category": "Köfte",
    "shortDescription": "Hocapaşa'nın asırlık balkan köftecisi.",
    "description": "1893 yılında açılan sadece bir avuç masası olan bu minik dükkan, yoğurulurken az baharat konulup ızgarada pişen ikonik Bulgaristan göçmeni köftesiyle bilinir.",
    "lat": 41.013700,
    "lng": 28.976300,
    "address": "Hoca Paşa, Hoca Paşa Sk. No:3, 34110 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1627308595229-7830f5c90683?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "11:30 - 21:00", "phoneNumber": "+90 212 494 46 40", "enCategory": "Meatball", "enShortDescription": "Hocapaşa's centuries-old Balkan meatball restaurant.", "enDescription": "Opened in 1893, this tiny shop with only a handful of tables is known for its iconic Bulgarian immigrant meatballs, which are cooked on the grill with a little seasoning while kneading." },
  {
    "id": "borisin-yeri",
    "name": "Boris'in Yeri",
    "category": "Kahvaltı, Mandıra",
    "shortDescription": "Kumkapı'da 1932'den beri hizmet veren tarihi mandıra ve kahvaltıcı.",
    "description": "Özellikle kendi yaptıkları manda kaymağı, balı, peynirleri ve sahanda yumurtasıyla salaş, nostaljik ve efsanevi bir kahvaltı mekanıdır.",
    "lat": 41.004000,
    "lng": 28.960000,
    "address": "Şehsuvar Bey, Ördekli Bakkal Sk. No:9, 34130 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "07:00 - 22:00", "phoneNumber": "+90 216 501 49 45", "enCategory": "Breakfast, Dairy", "enShortDescription": "Historical dairy and breakfast place serving in Kumkapı since 1932.", "enDescription": "It is a casual, nostalgic and legendary breakfast place, especially with its own buffalo cream, honey, cheese and fried eggs." },
  {
    "id": "hunkar",
    "name": "Hünkar Lokantası",
    "category": "Esnaf Lokantası, Osmanlı",
    "shortDescription": "Nişantaşı'nda rafine esnaf lokantası konsepti.",
    "description": "Beyaz masa örtüleri üzerinde Hünkar Beğendi, zeytinyağlılar ve paça çorbasıyla lüks ama bir o kadar da geleneksel lezzetler sunan eşsiz lokanta.",
    "lat": 41.050500,
    "lng": 28.992600,
    "address": "Harbiye, Mim Kemal Öke Cd. No:21, 34367 Şişli/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544148103-0773d1052bfc?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:30 - 22:30", "phoneNumber": "+90 212 508 52 50", "enCategory": "Esnaf Restaurant, Ottoman", "enShortDescription": "Refined tradesman restaurant concept in Nişantaşı.", "enDescription": "A unique restaurant that offers luxurious yet traditional tastes with Hünkar Beğendi, olive oil dishes and leg soup on white tablecloths." },
  {
    "id": "asitane",
    "name": "Asitane Restaurant",
    "category": "Osmanlı Saray Mutfağı",
    "shortDescription": "Kariye Müzesi gölgesinde unutulmuş saray tarifleri.",
    "description": "Tarihi kaynaklardan, saray ziyafet defterlerinden çıkarılıp uyarlanan 'Kavun Dolması', 'Mutancana' gibi çok özel Osmanlı yemeklerini en iyi sunan mekandır.",
    "lat": 41.031000,
    "lng": 28.938500,
    "address": "Dervişali, Kariye Cami Sk. No:6, 34087 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "12:00 - 23:30", "phoneNumber": "+90 216 515 55 55", "enCategory": "Ottoman Palace Cuisine", "enShortDescription": "Palace recipes forgotten in the shadow of the Kariye Museum.", "enDescription": "It is the place that best serves very special Ottoman dishes such as 'Melon Dolması' and 'Mutancana', which are extracted and adapted from historical sources and palace banquet books." },
  {
    "id": "cafer-erol",
    "name": "Şekerci Cafer Erol",
    "category": "Şekerleme, Tatlı",
    "shortDescription": "Kadıköy Çarşı'sının vitriniyle büyüleyen şekerlemecisi.",
    "description": "Özellikle bayram ve yılbaşı dönemlerinde masalsı vitrinleriyle dikkat çeken, Osmanlı usulü akide şekeri, lokum, ezme ve heykelsi tatlıların adresidir.",
    "lat": 40.990200,
    "lng": 29.025000,
    "address": "Osmanağa, Yasa Cd. No:19, 34714 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1520188740392-62fedadced86?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "08:00 - 00:00", "phoneNumber": "+90 212 522 58 60", "enCategory": "Confectionery, Dessert", "enShortDescription": "The confectioner who fascinates with his showcase in Kadıköy Bazaar.", "enDescription": "It is the address of Ottoman-style hard candy, Turkish delight, paste and sculptural desserts, which attract attention with its fairy-tale showcases, especially during the holidays and New Year's periods." },
  {
    "id": "karakoy-lokantasi",
    "name": "Karaköy Lokantası",
    "category": "Meyhane, Restoran",
    "shortDescription": "Turkuaz çinileriyle ünlü Karaköy modern meyhanesi.",
    "description": "Öğlenleri muazzam bir esnaf lokantası, akşamları ise şık ve modern bir meyhaneye dönüşen, kaliteli meze ve yemekleriyle ödüllü mekandır.",
    "lat": 41.024000,
    "lng": 28.976500,
    "address": "Kemankeş Karamustafa Paşa, Kemankeş Cd. No:33/A, 34425 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "12:00 - 00:00", "phoneNumber": "+90 216 529 61 65", "enCategory": "Tavern, Restaurant", "enShortDescription": "Karaköy modern tavern, famous for its turquoise tiles.", "enDescription": "It is an award-winning place with its quality appetizers and meals, turning into a magnificent tradesmen's restaurant at noon and a stylish and modern tavern in the evenings." },
  {
    "id": "barba-vasilis",
    "name": "Barba Vasilis",
    "category": "Rum Meyhanesi",
    "shortDescription": "Balat'ta tarihi bir Rum meyhanesi.",
    "description": "Haliç manzarasına karşı, Rum mezeleri, deniz ürünleri ve nostaljik atmosferiyle İstanbul'un çok kültürlü yeme içme mirasını yaşatan mekan.",
    "lat": 41.031500,
    "lng": 28.948000,
    "address": "Balat, Abdülezelpaşa Cd. No:97, 34087 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559466273-d95e72debaf8?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "13:00 - 01:00", "phoneNumber": "+90 212 536 64 70", "enCategory": "Greek Tavern", "enShortDescription": "A historical Greek tavern in Balat.", "enDescription": "The place that keeps the multicultural food and beverage heritage of Istanbul alive with its Greek appetizers, seafood and nostalgic atmosphere, against the view of the Golden Horn." },
  {
    "id": "cikolata-dukkani",
    "name": "Çikolata Dükkanı",
    "category": "Tatlı, Çikolata",
    "shortDescription": "Moda sokaklarına çikolata kokusu getiren küçük dükkan.",
    "description": "Eritilmiş Belçika çikolatası ve taze çileklerin buluştuğu ufak kaselerde sunulan tatlılarıyla günün her saati müdavimlerini ağırlayan popüler dükkan.",
    "lat": 40.982000,
    "lng": 29.026000,
    "address": "Caferağa, Yeni Fikir Sk. No:1, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "10:00 - 01:00", "phoneNumber": "+90 216 543 67 75", "enCategory": "Dessert, Chocolate", "enShortDescription": "The small shop that brings the smell of chocolate to the streets of fashion.", "enDescription": "A popular shop that welcomes its regulars at all hours of the day with its desserts served in small bowls of melted Belgian chocolate and fresh strawberries." },
  {
    "id": "halil-lahmacun",
    "name": "Halil Lahmacun",
    "category": "Lahmacun",
    "shortDescription": "Kadıköy Balık Pazarı içinde incecik, sarımsaksız lahmacun.",
    "description": "Sadece lahmacun ve peynirli pide satan, yıllardır değişmeyen çıtır çıtır ve hafif lahmacunuyla Anadolu yakasının tartışmasız lideridir.",
    "lat": 40.988800,
    "lng": 29.024000,
    "address": "Caferağa, Güneşli Bahçe Sk. No:26, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1551024506-0cb7e69f8ed1?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "11:30 - 21:00", "phoneNumber": "+90 212 550 70 80", "enCategory": "Lahmacun", "enShortDescription": "Thin, garlic-free lahmacun at Kadıköy Fish Market.", "enDescription": "Selling only lahmacun and cheese pita, it is the undisputed leader of the Anatolian side with its crispy and light lahmacun that has not changed for years." },
  {
    "id": "beyti",
    "name": "Beyti",
    "category": "Et Lokantası",
    "shortDescription": "Florya'nın ikonik et lokantası.",
    "description": "Etin en lezzetli halini sunan, geleneksel Türk misafirperverliği ile ünlü efsanevi restoran.",
    "lat": 40.9754,
    "lng": 28.7909,
    "address": "Şenlikköy, Orman Sk. No:8, 34153 Bakırköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "11:30 - 23:00", "phoneNumber": "+90 216 557 73 85", "enCategory": "Steakhouse", "enShortDescription": "Florya's iconic steakhouse.", "enDescription": "The legendary restaurant that offers the most delicious meat and is famous for its traditional Turkish hospitality." },
  {
    "id": "karismasen",
    "name": "Karısmma Sen",
    "category": "Meyhane",
    "shortDescription": "Ahırkapı'da nostaljik bir meyhane.",
    "description": "Tarihi atmosferi ve meşhur mezeleriyle eski İstanbul meyhane kültürünü yaşatan özel bir mekan.",
    "lat": 41.0028,
    "lng": 28.9839,
    "address": "Cankurtaran, Ahırkapı Cd. No:28, 34122 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "15:00 - 01:00", "phoneNumber": "+90 212 564 76 90", "enCategory": "Pub", "enShortDescription": "A nostalgic tavern in Ahırkapı.", "enDescription": "It is a special place that keeps the old Istanbul tavern culture alive with its historical atmosphere and famous appetizers." },
  {
    "id": "agora-meyhanesi",
    "name": "Agora Meyhanesi",
    "category": "Meyhane",
    "shortDescription": "Balat'ın 1890'dan beri değişmeyen yüzü.",
    "description": "Şarkılara konu olmuş, Rum ve Ermeni meze kültürünü bir asırdır aynı yerde sunan tarihi meyhane.",
    "lat": 41.0312,
    "lng": 28.9463,
    "address": "Balat, Mürselpaşa Cd. No:185, 34087 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "14:00 - 00:00", "phoneNumber": "+90 216 571 79 95", "enCategory": "Pub", "enShortDescription": "The unchanging face of Balat since 1890.", "enDescription": "A historical tavern that has been the subject of songs and has been serving Greek and Armenian appetizer culture in the same place for a century." },
  {
    "id": "safiye-sultan",
    "name": "Safiye Sultan",
    "category": "Cafe",
    "shortDescription": "Boğaz kıyısında huzurlu bir çay molası.",
    "description": "Denize sıfır konumu ve eşsiz manzarasıyla çayınızı yudumlarken İstanbul'un tadını çıkarabilirsiniz.",
    "lat": 41.0375,
    "lng": 29.0068,
    "address": "Salacak, Salacak İskele Cd. No:18, 34668 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559466273-d95e72debaf8?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "08:00 - 23:00", "phoneNumber": "+90 212 578 82 10", "enCategory": "Café", "enShortDescription": "A peaceful tea break on the Bosphorus shore.", "enDescription": "You can enjoy Istanbul while sipping your tea with its seaside location and unique view." },
  {
    "id": "nevizade",
    "name": "Nevizade",
    "category": "Meyhane Sokağı",
    "shortDescription": "Beyoğlu'nun kalbinde meyhane kültürü.",
    "description": "Yan yana dizilmiş meyhaneleri, sokak çalgıcıları ve eşsiz atmosferiyle İstanbul gece hayatının kalbi.",
    "lat": 41.0345,
    "lng": 28.9778,
    "address": "Hüseyinağa, Nevizade Sk., 34435 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1525648199074-cee30ba79a4a?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "16:00 - 04:00", "phoneNumber": "+90 216 585 85 15", "enCategory": "Meyhane Street", "enShortDescription": "Tavern culture in the heart of Beyoğlu.", "enDescription": "It is the heart of Istanbul nightlife with its taverns lined up side by side, street musicians and its unique atmosphere." },
  {
    "id": "pierre-loti",
    "name": "Pierre Loti Tepesi",
    "category": "Kahvehane, Manzara",
    "shortDescription": "Haliç'e tepeden bakan tarihi kahve.",
    "description": "Adını Fransız yazardan alan, Haliç'in eşsiz manzarasına karşı kahve içilebilecek en güzel tepelerden biri.",
    "lat": 41.0537,
    "lng": 28.9343,
    "address": "Eyüp Merkez, İdris Köşkü Cd., 34050 Eyüpsultan/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "08:00 - 00:00", "phoneNumber": "+90 212 592 88 20", "enCategory": "Coffeehouse, View", "enShortDescription": "Historical coffeehouse overlooking the Golden Horn.", "enDescription": "Named after the French writer, it is one of the most beautiful hills where you can drink coffee against the unique view of the Golden Horn." },
  {
    "id": "suleymaniye-kuru",
    "name": "Erzincanlı Ali Baba (Şube)",
    "category": "Kurufasulye",
    "shortDescription": "Tarihi Süleymaniye kurufasulyecisi.",
    "description": "Süleymaniye'nin meşhur kurufasulye dükkanlarının o mistik havasında eşsiz bir lezzet deneyimi.",
    "lat": 41.0152,
    "lng": 28.9631,
    "address": "Süleymaniye, Prof. Sıddık Sami Onar Cd., 34116 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "09:00 - 20:00", "phoneNumber": "+90 216 599 91 25", "enCategory": "beans", "enShortDescription": "Historical Suleymaniye dried beans seller.", "enDescription": "A unique taste experience in the mystical atmosphere of Suleymaniye's famous bean shops." },
  {
    "id": "galata-konak",
    "name": "Galata Konak Cafe",
    "category": "Cafe",
    "shortDescription": "Galata Kulesi manzaralı eşsiz teras.",
    "description": "Tarihi Galata çevresinin en güzel manzarasına sahip şık ve huzurlu teras kafesi.",
    "lat": 41.0258,
    "lng": 28.9744,
    "address": "Bereketzade, Hacı Ali Sk. No:2, 34421 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1549491689-d10292bc9da6?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "09:00 - 00:00", "phoneNumber": "+90 212 606 94 30", "enCategory": "Café", "enShortDescription": "Unique terrace with view of Galata Tower.", "enDescription": "Stylish and peaceful terrace cafe with the best view of the historical Galata surroundings." },
  {
    "id": "tarihi-cumhuriyet",
    "name": "Tarihi Cumhuriyet Meyhanesi",
    "category": "Meyhane",
    "shortDescription": "Atatürk'ün de ziyaret ettiği asırlık meyhane.",
    "description": "Canlı fasıl eşliğinde, tarihi bir dokuda harika Türk mezeleri.",
    "lat": 41.0348,
    "lng": 28.9781,
    "address": "Hüseyinağa, Sahne Sk. No:47, 34435 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "14:00 - 02:00", "phoneNumber": "+90 216 613 97 35", "enCategory": "Pub", "enShortDescription": "A century-old tavern that Atatürk also visited.", "enDescription": "Great Turkish appetizers with a historical texture, accompanied by live music." },
  {
    "id": "modatar",
    "name": "Moda Teras",
    "category": "Cafe, Restoran",
    "shortDescription": "Moda'nın huzurlu manzarası.",
    "description": "Kalamış ve Adalar manzarasına karşı kahvaltı yapmak veya kahve yudumlamak için ideal bir mekan.",
    "lat": 40.9782,
    "lng": 29.0234,
    "address": "Caferağa, Moda Mektebi Sk. No:1, 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559466273-d95e72debaf8?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "09:00 - 00:00", "phoneNumber": "+90 212 620 10 40", "enCategory": "Cafe, Restaurant", "enShortDescription": "The peaceful view of Moda.", "enDescription": "It is an ideal place to have breakfast or sip coffee against the view of Kalamış and the Princes' Islands." },
  {
    "id": "balat-kapi",
    "name": "Balat Kapı Köftecisi",
    "category": "Köfte",
    "shortDescription": "Renkli Balat sokaklarında enfes köfte.",
    "description": "Tarihi ve renkli Balat sokaklarını gezerken uğrayabileceğiniz ikonik köşelerden biri.",
    "lat": 41.0321,
    "lng": 28.9482,
    "address": "Balat, Mürselpaşa Cd., 34087 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:00 - 20:00", "phoneNumber": "+90 216 627 13 45", "enCategory": "Meatball", "enShortDescription": "Delicious meatballs on the colorful streets of Balat.", "enDescription": "It is one of the iconic corners you can visit while wandering the historical and colorful streets of Balat." },
  {
    "id": "kizta",
    "name": "Kıztaşı Muhallebicisi",
    "category": "Sütlü Tatlı",
    "shortDescription": "Geleneksel Fatih tatlıcısı.",
    "description": "Eski İstanbul sütlü tatlı kültürünü yaşatan samimi bir esnaf dükkanı.",
    "lat": 41.0146,
    "lng": 28.9515,
    "address": "İskenderpaşa, Kıztaşı Cd., 34081 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1542861619-756184ce1bfb?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "08:00 - 23:00", "phoneNumber": "+90 212 634 16 50", "enCategory": "Milky Dessert", "enShortDescription": "Traditional Fatih dessert shop.", "enDescription": "A friendly tradesmen's shop that keeps the old Istanbul milk dessert culture alive." },
  {
    "id": "cengel",
    "name": "Seval Pastanesi",
    "category": "Pastane",
    "shortDescription": "Çengelköy'ün efsanevi pastanesi.",
    "description": "Eşsiz poğaçaları ve sabah erkenden çıkan sıcak börekleriyle ünlü semt pastanesi.",
    "lat": 41.0494,
    "lng": 29.0515,
    "address": "Çengelköy, Çengelköy Cd., 34680 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1605807646983-377bc5a76493?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "06:00 - 22:00", "phoneNumber": "+90 216 641 19 55", "enCategory": "Patisserie", "enShortDescription": "The legendary patisserie of Çengelköy.", "enDescription": "The neighborhood patisserie famous for its unique pastries and hot pastries served early in the morning." },
  {
    "id": "galatab",
    "name": "Tarihi Galata Simitçisi",
    "category": "Fırın, Simit",
    "shortDescription": "Galata Kulesi altında mis kokulu simitler.",
    "description": "Odun ateşinde pişen, bol susamlı, İstanbul simidinin en iyi temsilcilerinden.",
    "lat": 41.0253,
    "lng": 28.9748,
    "address": "Bereketzade, Mumhane Cd., 34421 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "06:00 - 18:00", "phoneNumber": "+90 212 648 22 60", "enCategory": "Bakery, Bagel", "enShortDescription": "Fragrant bagels under the Galata Tower.", "enDescription": "One of the best representatives of Istanbul simit, cooked over wood fire and with plenty of sesame seeds." },
  {
    "id": "sur-kebap",
    "name": "Sur Ocakbaşı",
    "category": "Kebap",
    "shortDescription": "Fatih'te gerçek Güneydoğu lezzetleri.",
    "description": "Büryan kebabı ve etli pideleriyle meşhur, salaş ama lezzetli bir ocakbaşı deneyimi.",
    "lat": 41.0185,
    "lng": 28.9482,
    "address": "İskenderpaşa, Sofular Cd., 34081 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1626081156828-56eb0f5761a6?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "11:30 - 00:00", "phoneNumber": "+90 216 655 25 65", "enCategory": "Kebab", "enShortDescription": "Real Southeastern flavors in Fatih.", "enDescription": "A shabby but delicious Ocakbaşı experience, famous for its Büryan kebab and meaty pitas." },
  {
    "id": "kirecburnu",
    "name": "Kireçburnu Fırını",
    "category": "Fırın",
    "shortDescription": "Boğaz'ın meşhur börek fırını.",
    "description": "Sabah saatlerinde eşsiz boğaz manzarasına karşı kıtır kıtır börek yemek için harika bir yer.",
    "lat": 41.1444,
    "lng": 29.0494,
    "address": "Kireçburnu, Haydar Aliyev Cd., 34457 Sarıyer/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1616149955740-424a50f14652?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "06:00 - 22:00", "phoneNumber": "+90 212 662 28 70", "enCategory": "Oven", "enShortDescription": "Famous pastry bakery of the Bosphorus.", "enDescription": "It is a great place to eat crunchy pastries in the morning with a unique view of the Bosphorus." },
  {
    "id": "matbah",
    "name": "Matbah",
    "category": "Osmanlı",
    "shortDescription": "Topkapı Sarayı'nın hemen yanı başında.",
    "description": "Tarihin tozlu raflarından çıkarılan gerçek saray mutfağı yemeklerini lüks bir ambiyansta sunan restoran.",
    "lat": 41.0084,
    "lng": 28.9798,
    "address": "Cankurtaran, Caferiye Sk., 34122 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1548943487-a2e4b43b5851?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "12:00 - 23:00", "phoneNumber": "+90 216 669 31 75", "enCategory": "Ottoman", "enShortDescription": "Right next to Topkapi Palace.", "enDescription": "The restaurant offers real palace cuisine, taken from the dusty shelves of history, in a luxurious ambiance." },
  {
    "id": "haskral",
    "name": "Has Kral Hatay Sofrası",
    "category": "Yöresel",
    "shortDescription": "Aksaray'da Hatay mutfağının incisi.",
    "description": "Tuzda tavuk ve tepsi kebabıyla oldukça ünlü bol kepçeli restoran.",
    "lat": 41.0108,
    "lng": 28.9484,
    "address": "İskenderpaşa, Atatürk Blv., 34081 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:00 - 00:00", "phoneNumber": "+90 212 676 34 80", "enCategory": "Regional", "enShortDescription": "The pearl of Hatay cuisine in Aksaray.", "enDescription": "A restaurant with plenty of ladles, famous for its salted chicken and tray kebab." },
  {
    "id": "haci-sayid",
    "name": "Hacı Sayid",
    "category": "Tatlı, Baklava",
    "shortDescription": "Şirinevler'in efsane tatlıcısı.",
    "description": "Yıllardır kalitesini bozmadan günlük ve taze baklavalarıyla Avrupa yakasında sevilen marka.",
    "lat": 40.9926,
    "lng": 28.8452,
    "address": "Şirinevler, Mahmutbey Cd., 34188 Bahçelievler/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1598165039281-2292f392ddb1?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "07:00 - 00:00", "phoneNumber": "+90 216 683 37 85", "enCategory": "Dessert, Baklava", "enShortDescription": "The legendary dessert shop of Şirinevler.", "enDescription": "It has been a popular brand on the European side for years with its daily and fresh baklava without compromising its quality." },
  {
    "id": "yusuf-usta",
    "name": "Kebapçı Yusuf Usta",
    "category": "Kebap",
    "shortDescription": "Kadıköy Hasanpaşa'da kebap klasiği.",
    "description": "Gerçek Adana lezzetini İstanbul'a getiren ve sürekli kalabalık olan salaş mekan.",
    "lat": 40.9934,
    "lng": 29.0436,
    "address": "Hasanpaşa, Kurbağalıdere Cd., 34722 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1626081156828-56eb0f5761a6?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "11:00 - 22:30", "phoneNumber": "+90 212 690 40 90", "enCategory": "Kebab", "enShortDescription": "Kebab classic in Kadıköy Hasanpaşa.", "enDescription": "A shabby place that brings the real taste of Adana to Istanbul and is always crowded." },
  {
    "id": "corlulu",
    "name": "Çorlulu Ali Paşa Medresesi",
    "category": "Kafe, Nargile",
    "shortDescription": "Çemberlitaş'ta tarihi huzur.",
    "description": "Tarihin kokusunu içinize çekerken meşhur elma çayı ve Türk kahvesinin tadına varın.",
    "lat": 41.0094,
    "lng": 28.9712,
    "address": "Mollafenari, Divan Yolu Cd., 34120 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "09:00 - 02:00", "phoneNumber": "+90 216 697 43 95", "enCategory": "Cafe, Hookah", "enShortDescription": "Historical peace in Çemberlitaş.", "enDescription": "Enjoy the famous apple tea and Turkish coffee while breathing in the scent of history." },
  {
    "id": "akdeniz",
    "name": "Akdeniz Hatay Sofrası",
    "category": "Yöresel",
    "shortDescription": "Fatih'te gerçek bir gastro-şölen.",
    "description": "Sayısız çeşit mezesi ve yöresel Hatay peynirleriyle hazırlanmış kahvaltılarıyla meşhur.",
    "lat": 41.0145,
    "lng": 28.9416,
    "address": "İskenderpaşa, Ahmediye Cd., 34081 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "08:30 - 23:30", "phoneNumber": "+90 212 704 46 10", "enCategory": "Regional", "enShortDescription": "A real gastro-feast in Fatih.", "enDescription": "It is famous for its countless kinds of appetizers and breakfasts prepared with local Hatay cheeses." },
  {
    "id": "beykoz-dere",
    "name": "Beykoz Dereli",
    "category": "Balık",
    "shortDescription": "Beykoz'da sakin bir balık molası.",
    "description": "Geniş deniz ürünleri çeşitliliği ile Boğaz'ın havasını solumak isteyenlerin adresi.",
    "lat": 41.1356,
    "lng": 29.0886,
    "address": "Yalıköy, Boğaziçi Cd., 34820 Beykoz/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "12:00 - 00:00", "phoneNumber": "+90 216 711 49 15", "enCategory": "Fish", "enShortDescription": "A quiet fishing break in Beykoz.", "enDescription": "It is the address of those who want to breathe the air of the Bosphorus with its wide variety of seafood." },
  {
    "id": "divan-pub",
    "name": "Divan Pub Bebek",
    "category": "Kafe, Restoran",
    "shortDescription": "Bebek'in en klasik ve nezih mekanı.",
    "description": "Şık tasarımı ve muhteşem manzarasıyla uzun hafta sonu kahvaltılarının favorisi.",
    "lat": 41.0768,
    "lng": 29.0438,
    "address": "Bebek, Cevdet Paşa Cd., 34342 Beşiktaş/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1495147466023-af5c19cb3738?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "08:00 - 00:00", "phoneNumber": "+90 212 718 52 20", "enCategory": "Cafe, Restaurant", "enShortDescription": "The most classic and decent place in Bebek.", "enDescription": "It is a favorite for long weekend breakfasts with its stylish design and magnificent view." },
  {
    "id": "kizkulesi",
    "name": "Kız Kulesi Restoran",
    "category": "Lüks",
    "shortDescription": "İstanbul'un en simgesel yapısında yemek.",
    "description": "Marmara Denizi'nin ortasında eşsiz 360 derece İstanbul manzarası ile unutulmaz bir akşam.",
    "lat": 41.0211,
    "lng": 29.0041,
    "address": "Salacak, Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1548943487-a2e4b43b5851?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "10:00 - 00:00", "phoneNumber": "+90 216 725 55 25", "enCategory": "Luxury", "enShortDescription": "Dining in Istanbul's most iconic building.", "enDescription": "An unforgettable evening with a unique 360 ​​degree view of Istanbul in the middle of the Marmara Sea." },
  {
    "id": "ortakoy-kumpir",
    "name": "Ortaköy Kumpircileri",
    "category": "Sokak Lezzeti",
    "shortDescription": "Boğaz Köprüsü altında eşsiz kumpir.",
    "description": "Ortaköy meydanında yan yana dizilmiş kumpircilerin birbirinden renkli tezgahları.",
    "lat": 41.0475,
    "lng": 29.0264,
    "address": "Ortaköy, Mecidiye Köprüsü Sk., 34347 Beşiktaş/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1564613467268-bf0ddb3c220f?auto=format&fit=crop&w=800&q=80",
    "rating": 4.2,
    "workingHours": "10:00 - 03:00", "phoneNumber": "+90 212 732 58 30", "enCategory": "Street Taste", "enShortDescription": "Unique kumpir under the Bosphorus Bridge.", "enDescription": "Colorful stalls of kumpir sellers lined up side by side in Ortaköy square." },
  {
    "id": "vayvaline",
    "name": "Tarihi Kuzguncuk Fırını",
    "category": "Fırın",
    "shortDescription": "Kuzguncuk'un nostaljik havası.",
    "description": "Simiti ve un kurabiyesi ile meşhur, sanatçıların ve semt sakinlerinin uğrak yeri.",
    "lat": 41.0336,
    "lng": 29.0298,
    "address": "Kuzguncuk, İcadiye Cd., 34674 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1605807646983-377bc5a76493?auto=format&fit=crop&w=800&q=80",
    "rating": 4.7,
    "workingHours": "06:00 - 21:00", "phoneNumber": "+90 216 739 61 35", "enCategory": "Oven", "enShortDescription": "The nostalgic atmosphere of Kuzguncuk.", "enDescription": "Famous for its simiti and flour cookies, it is a frequent destination for artists and neighborhood residents." },
  {
    "id": "bostanci-donut",
    "name": "Bostancı Hatay Dürüm",
    "category": "Dürüm",
    "shortDescription": "Gececilerin gözde adresi.",
    "description": "Dürümü ve özel sosuyla Anadolu Yakasının popüler atıştırmalık noktası.",
    "lat": 40.9532,
    "lng": 29.0954,
    "address": "Bostancı, Bağdat Cd., 34744 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1626081156828-56eb0f5761a6?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "12:00 - 05:00", "phoneNumber": "+90 212 746 64 40", "enCategory": "Situation", "enShortDescription": "The favorite address of night people.", "enDescription": "A popular snack point on the Anatolian Side with its wraps and special sauce." },
  {
    "id": "kemal-usta",
    "name": "Kemal Usta Waffles",
    "category": "Tatlı",
    "shortDescription": "Moda sahilde vazgeçilmez tatlı.",
    "description": "Bol mazlemeli waffle denildiğinde Anadolu yakasında akla ilk gelen yerlerden.",
    "lat": 40.9842,
    "lng": 29.0256,
    "address": "Caferağa, Moda Cd., 34710 Kadıköy/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1542861619-756184ce1bfb?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "10:00 - 02:00", "phoneNumber": "+90 216 753 67 45", "enCategory": "Sweet", "enShortDescription": "An indispensable dessert on the fashionable beach.", "enDescription": "When it comes to waffles with lots of ingredients, it is one of the first places that come to mind on the Anatolian side." },
  {
    "id": "vogue",
    "name": "Vogue Restaurant",
    "category": "Lüks",
    "shortDescription": "Beşiktaş'ta panoramik boğaz manzarası.",
    "description": "Modern dünya mutfağı ve şık ambiyansıyla İstanbul'un özel ve elit mekanlarından.",
    "lat": 41.0428,
    "lng": 29.0006,
    "address": "Vişnezade, Akaretler Spor Cd. No:92, 34357 Beşiktaş/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "12:00 - 01:00", "phoneNumber": "+90 212 760 70 50", "enCategory": "Luxury", "enShortDescription": "Panoramic Bosphorus view in Beşiktaş.", "enDescription": "It is one of the special and elite places in Istanbul with its modern world cuisine and stylish ambiance." },
  {
    "id": "sevket",
    "name": "Tarihi Şevket Usta",
    "category": "Köfte",
    "shortDescription": "Küçükçekmece'de klasik köfte.",
    "description": "Sakin semtte lezziz ve bol sulu köftesi ile bilinir.",
    "lat": 40.9892,
    "lng": 28.7731,
    "address": "Fatih, İstanbul Cd., 34290 Küçükçekmece/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1627308595229-7830f5c90683?auto=format&fit=crop&w=800&q=80",
    "rating": 4.2,
    "workingHours": "11:30 - 22:00", "phoneNumber": "+90 216 767 73 55", "enCategory": "Meatball", "enShortDescription": "Classic meatballs in Küçükçekmece.", "enDescription": "It is known for its delicious and juicy meatballs in the quiet neighborhood." },
  {
    "id": "cihangir-cafe",
    "name": "Cihangir Kahvesi",
    "category": "Kahve",
    "shortDescription": "Semt sakinlerinin favori çay mekanı.",
    "description": "Muhteşem manzarası eşliğinde hafif tatlılar ve Türk çayı.",
    "lat": 41.0315,
    "lng": 28.9856,
    "address": "Cihangir, Firuzağa Cami Sk., 34433 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1577318182747-d586ea2deba4?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "08:00 - 00:00", "phoneNumber": "+90 212 774 76 60", "enCategory": "Coffee", "enShortDescription": "The favorite tea place of the neighborhood residents.", "enDescription": "Light desserts and Turkish tea accompanied by a magnificent view." },
  {
    "id": "kuzguncuk-balik",
    "name": "Kuzguncuk Balıkçısı",
    "category": "Balık",
    "shortDescription": "Şirin, salaş küçük bir mekan.",
    "description": "İstanbul boğazının balık kültürünü otantik şekilde hissettiren, samimi ve kaliteli balıkçı.",
    "lat": 41.0348,
    "lng": 29.0304,
    "address": "Kuzguncuk, İcadiye Cd., 34674 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "12:00 - 23:00", "phoneNumber": "+90 216 781 79 65", "enCategory": "Fish", "enShortDescription": "A cute, cozy little place.", "enDescription": "A friendly and quality fisherman who makes you feel the fish culture of the Bosphorus in an authentic way." },
  {
    "id": "polonezkoy",
    "name": "Leonardo Polonezköy",
    "category": "Doğa Mekanı",
    "shortDescription": "Doğa ile iç içe zengin menü.",
    "description": "Ağaçlar arasında, ahşap mimarisiyle et yemekleri ve köy kahvaltısı sunan huzurlu mekan.",
    "lat": 41.1118,
    "lng": 29.2122,
    "address": "Polonez, Cumhuriyet Cd., 34814 Beykoz/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "09:00 - 23:00", "phoneNumber": "+90 212 788 82 70", "enCategory": "Nature Place", "enShortDescription": "Rich menu intertwined with nature.", "enDescription": "A peaceful place among the trees, with its wooden architecture, serving meat dishes and village breakfast." },
  {
    "id": "nusr-et",
    "name": "Nusr-Et Steakhouse Etiler",
    "category": "Lüks Et",
    "shortDescription": "Şovlarıyla ünlü dünya çapındaki etçi.",
    "description": "Yüksek kaliteli et menüleri ve harika sunumlarıyla elit ve gösterişli restoran.",
    "lat": 41.0825,
    "lng": 29.0321,
    "address": "Etiler, Nispetiye Cd. No:87, 34337 Beşiktaş/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "12:00 - 01:00", "phoneNumber": "+90 216 795 85 75", "enCategory": "Luxury Meat", "enShortDescription": "Worldwide meatman famous for his shows.", "enDescription": "Elite and flashy restaurant with high quality meat menus and wonderful presentations." },
  {
    "id": "mikla",
    "name": "Mikla",
    "category": "Lüks",
    "shortDescription": "Pera'da Michelin yıldızlı deneyim.",
    "description": "Yeni Anadolu mutfağını modern tekniklerle harmanlayan, panoramik manzaralı seçkin mekan.",
    "lat": 41.0313,
    "lng": 28.9760,
    "address": "Asmalı Mescit, Meşrutiyet Cd. No:15, 34430 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80",
    "rating": 4.8,
    "workingHours": "18:00 - 01:00", "phoneNumber": "+90 212 802 88 80", "enCategory": "Luxury", "enShortDescription": "Michelin star experience in Pera.", "enDescription": "An exclusive venue with a panoramic view, blending New Anatolian cuisine with modern techniques." },
  {
    "id": "tarihi-incesu",
    "name": "Tarihi İncesu Meyhanesi",
    "category": "Meyhane",
    "shortDescription": "Yedikule'de unutulmaz meze masaları.",
    "description": "Geleneksel motifler ve neşeli kalabalığıyla ünlü, tarihi yarımadadaki samimi ortam.",
    "lat": 40.9945,
    "lng": 28.9213,
    "address": "Yedikule, Hacı Evhaddin Cd., 34107 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80",
    "rating": 4.3,
    "workingHours": "16:00 - 01:00", "phoneNumber": "+90 216 809 91 85", "enCategory": "Pub", "enShortDescription": "Unforgettable appetizer tables in Yedikule.", "enDescription": "A friendly atmosphere in the historical peninsula, famous for its traditional motifs and cheerful crowd." },
  {
    "id": "saray-muhallebi",
    "name": "Saray Muhallebicisi",
    "category": "Sütlü Tatlı",
    "shortDescription": "İstiklal'in klasikleşmiş tatlı durağı.",
    "description": "1935'ten beri tavukgöğsü ve kazandibi başta olmak üzere enfes sütlü tatlılar üreten tarihi adres.",
    "lat": 41.0354,
    "lng": 28.9802,
    "address": "Kuloglu, İstiklal Cd., 34433 Beyoğlu/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1559598467-f8b76c8105d0?auto=format&fit=crop&w=800&q=80",
    "rating": 4.5,
    "workingHours": "07:00 - 01:00", "phoneNumber": "+90 212 816 94 90", "enCategory": "Milky Dessert", "enShortDescription": "The classic dessert stop of Istiklal.", "enDescription": "The historical address that has been producing delicious milk desserts, especially chicken breast and Kazandibi, since 1935." },
  {
    "id": "uskudar-sahil",
    "name": "Üsküdar Sahil Büfesi",
    "category": "Sokak Lezzeti",
    "shortDescription": "Kızkulesine karşı sosisli ve çay.",
    "description": "Boğaz havası alırken ayak üstü atıştırmak isteyenler için vazgeçilmez bir sahil dinlencesi.",
    "lat": 41.0256,
    "lng": 29.0118,
    "address": "Mimar Sinan, Harem Sahilyolu, 34672 Üsküdar/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1564613467268-bf0ddb3c220f?auto=format&fit=crop&w=800&q=80",
    "rating": 4.4,
    "workingHours": "24 Saat Açık", "phoneNumber": "+90 216 823 97 95", "enCategory": "Street Taste", "enShortDescription": "Hot dogs and tea against the Maiden's Tower.", "enDescription": "An indispensable beach holiday for those who want to have a snack while taking in the Bosphorus air." },
  {
    "id": "hamdi-rest",
    "name": "Hamdi Restaurant",
    "category": "Kebap",
    "shortDescription": "Eminönü'nde Haliç ve Galata manzaralı efsane.",
    "description": "Uzun yıllardır fıstıklı kebabi, içli köftesi ve eşsiz manzarası ile nam salmış büyük restoran.",
    "lat": 41.0165,
    "lng": 28.9715,
    "address": "Rüstem Paşa, Tahmis Cd. No:71, 34116 Fatih/İstanbul",
    "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    "rating": 4.6,
    "workingHours": "11:30 - 00:00", "phoneNumber": "+90 212 830 10 10", "enCategory": "Kebab", "enShortDescription": "Legendary with a view of the Golden Horn and Galata in Eminönü.", "enDescription": "A large restaurant that has been famous for its pistachio kebab, stuffed meatballs and unique view for many years." },
  { "id": "mado-etiler", "name": "Mado Etiler", "category": "Tatlı, Dondurma", "shortDescription": "Maraş dondurması ve kahve keyfi.", "description": "Geleneksel Maraş dondurmasının İstanbul'daki şık mekanlarından biri.", "lat": 41.0820, "lng": 29.0300, "address": "Nispetiye Cad. No:99, Beşiktaş/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1559598467-f8b76c8105d0?auto=format&fit=crop&w=800&q=80", "rating": 4.2, "workingHours": "08:00 - 01:00", "phoneNumber": "+90 216 837 13 15", "enCategory": "Dessert, Ice Cream", "enShortDescription": "Enjoying Maraş ice cream and coffee.", "enDescription": "One of the stylish places for traditional Maraş ice cream in Istanbul." },
  { "id": "tarihi-cinar", "name": "Tarihi Çınaraltı Lokantası", "category": "Esnaf Lokantası", "shortDescription": "Galata'nın asırlık esnaf lokantası.", "description": "Meşhur zeytinyağlıları ve her gün değişen sulu yemek menüsüyle öğle yemeğinin vazgeçilmezi.", "lat": 41.0260, "lng": 28.9750, "address": "Galata Meydanı No:3, Beyoğlu/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "rating": 4.5, "workingHours": "11:30 - 21:00", "phoneNumber": "+90 212 844 16 20", "enCategory": "Esnaf Restaurant", "enShortDescription": "Galata's century-old tradesman restaurant.", "enDescription": "It is an indispensable part of lunch with its famous olive oil dishes and a menu of juicy dishes that changes every day." },
  { "id": "cengel-borek", "name": "Çengelköy Börekçisi", "category": "Börek", "shortDescription": "Çıtır çıtır taze peynirli su böreği.", "description": "Bölge halkının kahvaltı için uzun sıralar oluşturduğu popüler tarihi börekçi.", "lat": 41.0510, "lng": 29.0525, "address": "Çengelköy Meydanı No:12, Üsküdar/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1616149955740-424a50f14652?auto=format&fit=crop&w=800&q=80", "rating": 4.6, "workingHours": "06:00 - 22:00", "phoneNumber": "+90 216 851 19 25", "enCategory": "Pastry", "enShortDescription": "Crispy fresh cheese pastry.", "enDescription": "A popular historical pastry shop where locals line up for breakfast." },
  { "id": "bosphorus-grill", "name": "Bosphorus Grill", "category": "Izgara", "shortDescription": "Boğaz köprüsü altında nefis ızgara et.", "description": "Denize sıfır masalarda enfes ızgara çeşitleri sunan harika mekan.", "lat": 41.0456, "lng": 29.0232, "address": "Ortaköy Sahili, Beşiktaş/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80", "rating": 4.4, "workingHours": "12:00 - 23:30", "phoneNumber": "+90 212 858 22 30", "enCategory": "Grill", "enShortDescription": "Delicious grilled meat under the Bosphorus bridge.", "enDescription": "A wonderful place that offers delicious grill varieties at seaside tables." },
  { "id": "galata-simit", "name": "Tarihi Galata Simit Evi", "category": "Simit", "shortDescription": "Odun ateşinde gevrek simit.", "description": "İstanbul sokaklarının klasik atıştırmalığı olan sıcak simidi odun ateşinden sunar.", "lat": 41.0255, "lng": 28.9745, "address": "Galata Kulesi Altı Sk. Beyoğlu/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?auto=format&fit=crop&w=800&q=80", "rating": 4.8, "workingHours": "06:00 - 18:00", "phoneNumber": "+90 216 865 25 35", "enCategory": "Simit", "enShortDescription": "Crunchy bagels over wood fire.", "enDescription": "It serves hot bagels, the classic snack of Istanbul streets, from a wood fire." },
  { "id": "ali-usta-mondi", "name": "Moda Dondurmacısı Ali Usta", "category": "Dondurma", "shortDescription": "Moda'nın efsanevi dondurmacısı.", "description": "Yaz-kış önünde uzun kuyrukların olduğu, taze süt ve meyvelerle hazırlanan leziz dondurma.", "lat": 40.9845, "lng": 29.0260, "address": "Moda Caddesi No:264 Kadıköy/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1559598467-f8b76c8105d0?auto=format&fit=crop&w=800&q=80", "rating": 4.7, "workingHours": "10:00 - 02:00", "phoneNumber": "+90 212 872 28 40", "enCategory": "Ice cream", "enShortDescription": "Moda's legendary ice cream maker.", "enDescription": "Delicious ice cream prepared with fresh milk and fruits, with long queues in summer and winter." },
  { "id": "beyaz-firin", "name": "Beyaz Fırın Kadıköy", "category": "Fırın, Pastane", "shortDescription": "İki asırlık kahvaltı ve pasta durağı.", "description": "Geleneksel lezzetleri modern dokunuşlarla sunan tarihi pastane ve kafeterya.", "lat": 40.9905, "lng": 29.0255, "address": "Yasa Cd. No:23, Kadıköy/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1605807646983-377bc5a76493?auto=format&fit=crop&w=800&q=80", "rating": 4.6, "workingHours": "07:00 - 23:00", "phoneNumber": "+90 216 879 31 45", "enCategory": "Bakery, Patisserie", "enShortDescription": "A two-century-old breakfast and pastry stop.", "enDescription": "Historical patisserie and cafeteria offering traditional flavors with modern touches." },
  { "id": "pierre-loti-kahve", "name": "Aziyade Restoran", "category": "Restoran", "shortDescription": "Pierre Loti'de eşsiz Haliç manzarası.", "description": "Tarihi kahvenin hemen yanında, Haliç'e nazır seçkin Osmanlı lezzetleri sunan mekan.", "lat": 41.0538, "lng": 28.9340, "address": "İdris Köşkü Cd. Eyüpsultan/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80", "rating": 4.5, "workingHours": "10:00 - 23:00", "phoneNumber": "+90 212 886 34 50", "enCategory": "Restaurant", "enShortDescription": "Unique Golden Horn view in Pierre Loti.", "enDescription": "The place offers exclusive Ottoman flavors overlooking the Golden Horn, right next to the historical coffeehouse." },
  { "id": "uskudar-kanaat", "name": "Tarihi Üsküdar Kebapçısı", "category": "Kebap", "shortDescription": "Asırlık lezzet sırlarıyla yoğrulmuş kebap.", "description": "Anadolu yakasının en eski ve sevilen kebap duraklarından, samimi bir atmosfer.", "lat": 41.0265, "lng": 29.0150, "address": "Hakimiyeti Milliye Cd. Üsküdar/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1626081156828-56eb0f5761a6?auto=format&fit=crop&w=800&q=80", "rating": 4.4, "workingHours": "11:30 - 23:00", "phoneNumber": "+90 216 893 37 55", "enCategory": "Kebab", "enShortDescription": "Kebab kneaded with centuries-old taste secrets.", "enDescription": "A friendly atmosphere, one of the oldest and most popular kebab stops on the Anatolian side." },
  { "id": "emirgan-koru", "name": "Sarı Köşk Restoran", "category": "Restoran, Cafe", "shortDescription": "Emirgan Korusu içinde muazzam tabiat.", "description": "Tarihi köşkte zengin kahvaltı ve Türk mutfağından seçmeler doğa ile iç içe.", "lat": 41.1070, "lng": 29.0535, "address": "Emirgan Korusu İçi No:1, Sarıyer/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1577318182747-d586ea2deba4?auto=format&fit=crop&w=800&q=80", "rating": 4.6, "workingHours": "09:00 - 23:00", "phoneNumber": "+90 212 200 40 60", "enCategory": "Restaurant, Cafe", "enShortDescription": "Magnificent nature in Emirgan Grove.", "enDescription": "Rich breakfast and selections from Turkish cuisine in the historical mansion, intertwined with nature." },
  { "id": "camlica-tepesi", "name": "Çamlıca Sosyal Tesisleri", "category": "Kafeterya, Türk Mutfağı", "shortDescription": "Tepeden tüm İstanbul'a hakim.", "description": "Meşhur kumpiri, çayı ve muazzam Boğaz manzarasıyla nostaljik Çamlıca tepesi lezzetleri.", "lat": 41.0267, "lng": 29.0683, "address": "Turistik Çamlıca Cd. Üsküdar/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80", "rating": 4.5, "workingHours": "08:30 - 23:00", "phoneNumber": "+90 216 207 43 65", "enCategory": "Cafeteria, Turkish Cuisine", "enShortDescription": "It dominates all of Istanbul from the top.", "enDescription": "Nostalgic flavors of Çamlıca hill with its famous kumpiri, tea and magnificent Bosphorus view." },
  { "id": "beyoglu-cikolata", "name": "Tarihi Beyoğlu Çikolatacısı", "category": "Tatlı, Çikolata", "shortDescription": "İstiklal caddesi klasik atıştırmalığı.", "description": "Kağıda sarılı dev fındıklı çikolataların efsanevi dükkanı. Ayaküstü enerji deposu.", "lat": 41.0335, "lng": 28.9774, "address": "İstiklal Cd. No:69, Beyoğlu/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1542861619-756184ce1bfb?auto=format&fit=crop&w=800&q=80", "rating": 4.7, "workingHours": "10:00 - 00:00", "phoneNumber": "+90 212 214 46 70", "enCategory": "Dessert, Chocolate", "enShortDescription": "Istiklal street classic snack.", "enDescription": "The legendary shop of giant hazelnut chocolates wrapped in paper. A store of energy on your feet." },
  { "id": "bebek-kahve", "name": "Bebek Kahve", "category": "Kafe", "shortDescription": "Boğazın tam dibinde demli çay.", "description": "Sanatçıların ve yerel halkın sabah kahvesi veya akşamüstü çayı için değişmez samimi adresi.", "lat": 41.0766, "lng": 29.0435, "address": "Cevdet Paşa Cd. No:18, Beşiktaş/İstanbul", "imageUrl": "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80", "rating": 4.6, "workingHours": "07:00 - 01:00", "phoneNumber": "+90 216 221 49 75", "enCategory": "Cafe", "enShortDescription": "Strong tea right at the bottom of the Bosphorus.", "enDescription": "The unchanging friendly address of artists and locals for morning coffee or afternoon tea." }
];
